# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: ["hooks"]
#auto: true
pygments: true

title : Judy M. Vance
shorttitle: jmvance
baseurl: /~jmvance
shared: /share

safe: true
lsi: false
pygments: true
github-url: http://github.com/vancegroup

navlinks:
-
    text: Research
    page: /RESEARCH/index.html
    link: /RESEARCH/
-
    text: Publications
    page: /publications/index.html
    link: /htmls/publicat.htm
-
    text: Presentations
    page: /presentations/index.html
    link: /htmls/prsntt.htm
-
    text: Teaching
    page: /teaching/index.html
    link: /htmls/teaching.htm
-
    text: Students
    page: /students/index.html
    link: /htmls/students.htm
-
    text: Resume
    page: /resume/index.html
    link: /htmls/resume.htm


outlinks:
-
    acronym: ME
    text: Mechanical Engineering
    link: http://www.me.iastate.edu/
-
    acronym: VRAC
    text: Virtual Reality Applications Center
    link: http://www.vrac.iastate.edu/
-
    acronym: ISU
    text: Iowa State University
    link: http://www.iastate.edu/

# -
#    text: Judy M. Vance's Homepage
#    link: http://www.vrac.iastate.edu/~jmvance/
#-
#    text: Home
#    page: /index.html
#    link: /
	
