# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

exclude: ["hooks", ".git", ".gitignore"]
pygments: true

title : Judy M. Vance
baseurl: /~jmvance
shared: /share

url: http://public.vrac.iastate.edu
productionurl: http://public.vrac.iastate.edu

vrac-link: '<a href="http://www.vrac.iastate.edu/">Virtual Reality Applications Center</a>'

safe: true
lsi: true
pygments: true

navlinks:
-
    text: Research
    page: /RESEARCH/index.html
    link: /RESEARCH/
-
    text: Publications
    page: /publications/index.html
    link: /htmls/publicat.htm
-
    text: Presentations
    page: /presentations/index.html
    link: /htmls/prsntt.htm
-
    text: Teaching
    page: /teaching/index.html
    link: /htmls/teaching.htm
-
    text: Students
    page: /students/index.html
    link: /htmls/students.htm
-
    text: Resume
    page: /resume/index.html
    link: /htmls/resume.htm


outlinks:
-
    acronym: ME
    text: Mechanical Engineering
    link: http://www.me.iastate.edu/
-
    acronym: VRAC
    text: Virtual Reality Applications Center
    link: http://www.vrac.iastate.edu/
-
    acronym: ISU
    text: Iowa State University
    link: http://www.iastate.edu/


