#!/bin/bash -e

. $(dirname $0)/common.sh

(
	cd ${REPOROOT}
	mkdir -p "${FILEROOT}/"

	_scripts/run-jekyll
	_scripts/sync-dir-to-fileroot _oldsite/
	_scripts/sync-dir-to-fileroot _site/

	_scripts/perform-deletions

	_scripts/install-htaccess
)
