#!/bin/bash -e

. $(dirname $0)/common.sh

(
	cd ${REPOROOT}
	mkdir -p "${FILEROOT}/"

	_scripts/run-jekyll
	rsync -r -t -v --progress -l -z _oldsite/ "${FILEROOT}/"
	rsync -r -t -v --progress -l -z _site/ "${FILEROOT}/"

	_scripts/perform-deletions

	if ${HTACCESS}; then
		echo "- '${FILEROOT}/.htaccess' contents:"
		(cat _stub.htaccess; generate_redirects.lua) | tee "${FILEROOT}/.htaccess"
	fi
)
