#!/bin/bash -e

. $(dirname $0)/common.sh

(
	cd ${REPOROOT}

	if ${HTACCESS}; then
		echo "- installing '${FILEROOT}/.htaccess' with contents:"
		(cat _stub.htaccess; generate_redirects.lua) | tee "${FILEROOT}/.htaccess"
	else
		echo "- Skipping generation of .htaccess per config file"
	fi
)
