#!/bin/bash -e

export CONFIG=$(cd $(dirname $0) && cd config && pwd)/$1
[ -f ${CONFIG} ] || (echo "ERROR: Could not find config $1 -> '${CONFIG}' !" >&2; exit 1)

. ${CONFIG}
export DOMAIN
export WEBROOT
export FILEROOT
export HTACCESS
export INSTALLER


[ ! -z $2 ] || (echo "ERROR: Must pass a command to run!" >&2; exit 2)

$2
