#!/bin/sh

(
	cd $(dirname $0) && cd ..
	./_describe.sh --apply
	jekyll --base-url /vancegroup/jmvance-test --kramdown --url http://www.vrac.iastate.edu _site_preview
	code=$?
	./_describe.sh --unapply
	exit $?
	#rsync -r -t -v --progress --delete -l -z _site_preview/ keymaker.vrac.iastate.edu:/home/vr/apps/vancegroup/public_html/jmvance-test/
)
