#!/bin/bash
#
# An example hook script for the "post-receive" event.
#
# The "post-receive" script is run after receive-pack has accepted a pack
# and the repository has been updated.  It is passed arguments in through
# stdin in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master
#
# see contrib/hooks/ for a sample, or uncomment the next line and
# rename the file to "post-receive".

#. /usr/share/git-core/contrib/hooks/post-receive-email

REPOHOST="rpavlik@git.vrac.iastate.edu"
REPODIR="/git/$(basename $(cd $(dirname $0) && cd .. && pwd))"

REPO="${REPOHOST}:${REPODIR}"
#REPO="rpavlik@keymaker.vrac.iastate.edu:/home/vr/apps/vancegroup/git-repos/vancegroup-web.git"

echo "Notifying Jenkins to trigger a build... url=${REPO}"
curl --silent --show-error "https://no-salt.vrac.iastate.edu:8080/git/notifyCommit?url=${REPO}"

